# Generated by Django 5.1.4 on 2024-12-08 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 8, 11, 53, 26, 847268, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="listing_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 8, 11, 53, 26, 846647, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
