# Generated by Django 5.1.4 on 2024-12-12 15:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_cart_created_at_alter_product_listing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 12, 15, 47, 3, 394377, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="content.cart",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="listing_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 12, 15, 47, 3, 393809, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
