# Generated by Django 5.1.4 on 2024-12-12 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_cart_created_at_alter_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 12, 15, 49, 49, 115186, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="listing_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 12, 15, 49, 49, 114631, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
